### ISSUE TITLE
support for Markdown syntax

### ISSUE THREAD

**Issue by memo33** [memo33/sc4pac-tools#14]
The metadata text fields `description`, `warning`, `conflicts`, … should support Markdown syntax, 

This will enable several styling options like lists and URLs, as commonly used for Github .md documents.

It is a backward incompatible change, as the text wrapping/line breaking behavior differs. Instead of
```yaml
description: >
  line 1

  line 2

  line 3
```
or (equivalently)
```yaml
description: |
  line 1
  line 2
  line 3
```
as used used until now, going forward the following format should be used
```yaml
description: |
  line 1

  line 2

  line 3
```
All uses of `>` should be replaced by `|`. This ensures correct display of lines and paragraphs on the HTML pages and in the GUI, while also preserving lists and other structures.

I'm planning to write a script to update the existing metadata files accordingly.

@sebamarynissen @zasco

**Comment by sebamarynissen** [comment]
Great idea. I was thinking about this as well when I was adding all the Simmer2 content. My scraping script converts the html it finds in the description to markdown, so most of that content should already be compatible. I also tend to use | instead of > in my new contributions.

If you want I can give you a hand with the script, I have code in place that can traverse all metadata and perform modifications on it, including stylistic changes like changing > to | automatically. I use the npm [yaml](https://npm.im/yaml) for this.

**Comment by memo33** [comment]
> If you want I can give you a hand with the script, I have code in place that can traverse all metadata and perform modifications on it, including stylistic changes like changing > to | automatically. I use the npm [yaml](https://npm.im/yaml) for this.

I'd appreciate that a lot. So far I haven't looked into writing or modifying yaml files, as I only had to read their content.

**Comment by sebamarynissen** [comment]
I will try to have a look at it tomorrow. Could you just give an example on what the changes exactly should look like? Do I understand correctly that something like
```yaml
info:
  description: >
    Hello Simcitizen!
    I suggest you use sc4pac.

    I can go on here.
```
should be transformed into
```yaml
info:
  description: |
    Hello Simcitizen! I suggest you use sc4pac.

    I can ho on here.
```

**Comment by memo33** [comment]
Almost. I think the only changes necessary are either:
1. replace `>` by `|`, or
2. if the block already uses `|` and doesn't contain blank lines to separate paragraphs, then insert blank lines at every line break.

So (1)
```yaml
info:
  description: >
    Hello Simcitizen!
    I suggest you use sc4pac.

    I can go on here.
```
would be transformed into
```yaml
info:
  description: |
    Hello Simcitizen!
    I suggest you use sc4pac.

    I can go on here.
```
Similarly, (2)
```yaml
info:
  description: |
    Hello Simcitizen! I suggest you use sc4pac.
    I can go on here.
```
would be transformed into
```yaml
info:
  description: |
    Hello Simcitizen! I suggest you use sc4pac.

    I can go on here.
```
In both cases, the end result would be rendered the same, as single line breaks are wrapped in Markdown. Preserving the single line break between the first two lines in case (1) can help keep the yaml files and diffs more readable.

Come to think of it, this transformation is probably difficult to implement by reading the file as yaml, as that would immediately eliminate single line breaks in `>` blocks. It might be easier to operate on the raw text file instead. Let me know if this is a roadblock.

**Comment by sebamarynissen** [comment]
I've done some tests with my script, but the thing is that it also modifies stuff like formatting etc. For example,
```yaml
assets:
- assetId: foo
  include: ["/file.dat"]
```
gets transformed into
```yaml
assets:
  - assetId: foo
    include: [ "/file.dat" ]
```
meaning that the commit would become absolutely freaking *huge*. It might be better to just do a find-and-replace-all.

As for (2), I would actually not do this. I've noticed that stuff like
```yaml
description: |
  Nice lot eh? Lot stats:
   • Size: 2x2
   • Menu: landmarks
```
would become
```yaml
description: |
  Nice lot eh? Lot stats:

   • Size: 2x2

   • Menu: landmarks
```
That's definitely not desired behavior. An example of this in the metadata can be found in `angry-mozart:na-freight-cars-props`.

**Comment by Zasco** [comment]
> All uses of > should be replaced by |.

Good thing _[YamlEditorForSc4pac](https://github.com/noah-severyn/YamlEditorForSc4pac)_ already uses "**|**" then. _Markdown_ support will need to be added to the related fields however _@noah-severyn_. This shouldn't be too complicated, but will be done only when my ongoing [overhaul](https://github.com/noah-severyn/YamlEditorForSc4pac/issues/43) is.

**Comment by memo33** [comment]
> It might be better to just do a find-and-replace-all.

Yeah, I guess you're right. I'm going to look into it. Also good point about the edge cases. So far the repository shouldn't contain too many of these. I'll just fix those manually if necessary.

**Comment by memo33** [comment]
Alright, I've just made the switch in the main channel repository. The find/replace/manual-fixup approach was less complicated than expected.

For other channels there's no pressing need to migrate immediately. The change only becomes relevant once the updated GUI is released.
