### ISSUE TITLE
add support for more than one `website` in metadata

### ISSUE THREAD

**Issue by memo33** [memo33/sc4pac-tools#22]
An optional `websites` field should be added in addition to the `website` field.

This is mainly needed for filling the `externalIds` for STEX and SC4E files, in case a package is related to multiple external IDs. This would help with back-referencing from those websites to the relevant packages.

For example, the package `mattb325:house-15028r` could have three different external IDs:
- https://community.simtropolis.com/files/file/33176-craftsman-style-house/
- https://www.sc4evermore.com/index.php/downloads/download/11-residential/100-sc4d-lex-legacy-mattb325-residential-houses-pack-darknite
- https://www.sc4evermore.com/index.php/downloads/download/11-residential/101-sc4d-lex-legacy-mattb325-residential-houses-pack-maxisnite

~Alternatively, the external IDs could potentially be computed from the URLs of all assets referenced by a particular package. A downside is that this embeds more logic about the external URL format and requires the asset metadata to be present when building the channel.~

**Comment by memo33** [comment]
> Although this would be backward-breaking, wouldn't it be better to just have a websites field with the first value replacing the website field?

It's not backward-breaking to add a new field. Removing the `website` field would break backward-compatibility. I'd much prefer to have just a single field, but for backward-compatibility `website` could be kept.

> The assets would not necessarily reference all the websites of a package however...?

Ah, you're right. For example, when the same file has been uploaded to multiple exchanges.

**Comment by Zasco** [comment]
> Removing the `website` field would break backward-compatibility.

That was implied by my comment. I tend not to keep useless things.

> I'd much prefer to have just a single field, but for backward-compatibility website could be kept.

Me too! Maybe `website`  could be made optional?

**Comment by memo33** [comment]
> Maybe `website` could be made optional?

It's always been optional.
