### ISSUE TITLE
Implement metadata scheme version

### ISSUE THREAD

**Issue by Zasco** [memo33/sc4pac-tools#23]
With things rapidly changing lately, I thought that it may be time to start, somehow, versioning the metadata scheme as is already the case for the `sc4pac-channel-contents.json`.

Issue raised by https://github.com/memo33/sc4pac-tools/issues/22 and https://github.com/sebamarynissen/simtropolis-channel/issues/2.

**Comment by memo33** [comment]
If at some point a need for this arises, we can think about it, but currently there isn't, as all changes are mostly backward compatible. It helps that there is a conversion step from YAML to JSON, which can patch things on the fly. The latter is versioned via the "scheme" in the channel contents file. In case of incompatibilities, it forces users to upgrade their installation, or channel owners to rebuild their channels.

I'd like to avoid having to include a "scheme" number in every YAML file.

**Comment by Zasco** [comment]
> I'd like to avoid having to include a "scheme" number in every YAML file.

I get that, that's why I said "_somehow_".
